logging.level.root: INFO

spring.application.name: rtp-activator

# enable spring boot actuator health endpoint
management:
  endpoints:
    enabled-by-default: false
    web.exposure.include: health
  endpoint:
    health:
      enabled: true
      probes.enabled: true
#repository
  health.mongo.enabled: false

spring.data.mongodb:
  uri: ${COSMOS_ACCOUNT_RTP_CONNECTION_STRING:mongodb://localhost:27017}
  database: ${DB_NAME:rtp}
activation.base-url: ${BASE_URL:http://localhost}

# Enable general instrumentation
spring.cloud.azure.monitor.instrumentation.enabled: true

# Enable MongoDB specific instrumentation
spring.cloud.azure.monitor.instrumentation.mongo.enabled: true

# Enable reactor instrumentation (important for reactive stack)
spring.cloud.azure.monitor.instrumentation.reactor.enabled: true

service-provider:
  activation:
    api-version: v1
