logging.level:
  root: INFO

spring:
  application:
    name: rtp-activator
  data:
    mongodb:
      uri: ${COSMOS_ACCOUNT_RTP_CONNECTION_STRING:mongodb://localhost:27017}
      database: ${DB_NAME:rtp}

activation.base-url: ${BASE_URL:http://localhost}

# enable spring boot actuator health endpoint
management:
  endpoints:
    enabled-by-default: false
    web.exposure.include: health
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
  otlp:
    tracing:
      export:
        type: console
#repository
  health.mongo.enabled: false

service-provider:
  base-url: ${SP_BASE_URL:http://localhost:8080/rtps/}
  activation:
    api-version: v1
  send:
    epc-mock-url: ${EPC_MOCK_URL:https://api-rtp.dev.cstar.pagopa.it/rtp/mock}
    retry:
      max-attempts: ${EPC_SEND_RETRY_MAX_ATTEMPTS:3}
      backoff-min-duration: ${EPC_SEND_RETRY_BACKOFF_MIN_DURATION_MS:1000}
      backoff-jitter: ${EPC_SEND_RETRY_BACKOFF_JITTER:0.75}

otel:
  instrumentation:
    mongo:
      enabled: true



cache:
  params:
    - name: registry-data
      maximum-size: 1
      expire-after-write: 1d

blob-storage:
  storage-account-name: ${AZURE_STORAGE_ACCOUNT_NAME:cstardweurtpblobstorage}
  container-name: ${AZURE_STORAGE_CONTAINER_NAME:rtp-debtor-service-provider}
  blob-name: ${AZURE_BLOB_NAME:serviceregistry.json}
  managed-identity: ${IDENTITY_CLIENT_ID:}

client:
  client-secret-cbi: ${CLIENT_SECRET_CBI:test}
  ssl:
    pfx-file: MIIRTgIBAzCCEQoGCSqGSIb3DQEHAaCCEPsEghD3MIIQ8zCCBgwGCSqGSIb3DQEHAaCCBf0EggX5MIIF9TCCBfEGCyqGSIb3DQEMCgECoIIE/jCCBPowHAYKKoZIhvcNAQwBAzAOBAiDKQ3aWMHH/QICB9AEggTYGN7SvBSgS5WmvbDgju//sapX85bhjscW6tM5h9L0eNEImzLZVO5fKs7x+R+kwU3VT9mxBrX2O9c2bD09HCD/8paQRYilmNftG45RafUsQXyFhKgF9e2K84dsx5dzBEK7w6zwxXt+LUoXtyYp16vO9xokVmo75ftUg2bkR+MyfCAMXxJssbU6+fPBmzECVOg03MhlE2GbmaPrSnAxA3JltNnRvXNSg0D1+1Qnvi9rM1zJbqI2UEY/QTJxlwAmWvU2i9fpVKBZ74PC6uz6OVBUm6iJF4Vs0q17xIfiaFvVDdSRZC7jrho0g5JRjOqp8FohVSWSF/ivWRKoUdOghH7mjiGP0GCIYOsxasSXJwPnNI8ylyG41/cUKHw5nBdq6TCigAAHQ75dOpT1E0KBHYqkzFPaiupbf2ET23ujNtibf3DVdGaYzV96ZjKohBw1fwDDe/rVssdj95Hb8RD/JD6cmxSd0V25Ea8IZ033ahBIMExTHRBT2uhlSiZ6j1jZSsxNuvt3KjfrpqoM5inTQUwy5W3JtU8Dtp8bb9si/Y++PpujFEaRKe+P64aqtT4aALjXPha1mcn66d3qd3ORcgfRaBr5s8KseCiJGBBnlV8xlOEhcTDl1zO8jl7xIHvVHz2h+bGlVjG8D7WHBiMmSJSiZNhlESFl8Uq3iCArC38MVIVRs41AnWWuqukNNjkRbS0EAXWQG3taRimiLiV7GPOld1D3sMbqB4Ryd4yjt6vXgYyxIXjeKe+f6GumTYg4kdE1iNP5JxI3apwz7eQWCVf33ASMi4hshBNzdb9JrKyCvagL/qPhTqKxpfNFKwuGmHjv6rUgCpvJRI9llPFrBFVUeMIXdTML/nz2x+wuPS7lo0fyNuNdf9tLwfu9Qy8GA+vPsN1mR8v9GM8PtizVFFbFJMCyFWheFpbpbanVwUcexHarl9pdNda4qLyen9yHpKjgD9iWvs4fvnPkTwNSBc4MwsmYJXMRZ/WC5jOfAStxQ8X2ZtuR5nVMKQBa+1owBuG8hF1YN8BA9QcWy4/L9KObULjIu7yhuVHE+xrMqX1Rhdk/zgY1vFtv0hOFkfypVeoTOHzUKbhvJoo5XOdsuyZtMT7BVnNr5dJ6Y/dZCECh1460N1yX64HZnwHNBdRX+UUiEfgp99IvfM4GyfFxA3eFzOZSm1mWpDW5yeO64F8AwZ6zIqz/5l2N6Z1BPGt3O5fVhALZw5+BVfkc6XZOg/rOSxcnwTX7I0NN/OAXkxwRfjCUmTu7eLLxpyAYiL9kJMfhOE2o7d/kvImlr2wRdwMScTs18igP0mrEYrV1knicux0q5WpLQhss+B4vriUY+xPUG3H6lpJiJWcD99wHgU7MVrpc29Yji1su4YvA5ZI+TA0Fbvk8IYKCynLVged0ju8NaF3LJIyhxYazGRNiIMvuPyPvUObAMhTskG6y6vbVJog9olMVSb1PXikAyP2A2mzqWw+2Tm7BWfQkIsA5dy+PBybEX+PyDcUkazxQfXWYdETnDE8TEqd44zpreuvPiF401aUt67A9p3kRQ2Xm3J6F+fUg/diUH/lcPAXvlESixp4X4B4zgYZIOK7SdaQv4m/VSDmtL4lKr+kVN3gHsxfOmscQXaEh1IxARynMwRRQ2m5fZgO5ewGkMTGB3zATBgkqhkiG9w0BCRUxBgQEAQAAADBbBgkqhkiG9w0BCRQxTh5MAHsAMgA2ADAAMgA5AEEAMQA4AC0ARABEADUAMwAtADQAMgBBADgALQA4ADYAMwBBAC0AMwA0ADgANQBDAEEANgBEADUAQwAxAEUAfTBrBgkrBgEEAYI3EQExXh5cAE0AaQBjAHIAbwBzAG8AZgB0ACAARQBuAGgAYQBuAGMAZQBkACAAQwByAHkAcAB0AG8AZwByAGEAcABoAGkAYwAgAFAAcgBvAHYAaQBkAGUAcgAgAHYAMQAuADAwggrfBgkqhkiG9w0BBwagggrQMIIKzAIBADCCCsUGCSqGSIb3DQEHATAcBgoqhkiG9w0BDAEDMA4ECEhbzD8hMy+9AgIH0ICCCpjkTsb817PfYPX21yNOnhfykxFPr9ejbySONaif0Xbfqxw3NolGFX3BbrBZCFDLOivo/T+IMwa+7o8IQ2rLK5Np2J4DJ5WIg4B2Cc4cDdre63Hllh34HN5jDAYZnoixk1sbzhkv2xvD6KRviQSqDBd0yB3JXedZhtDwqzTeDj/CD3TGsrFcbCkb5w0SUSWhDeJ1W9CLtOenrZ7XDwipe+tdsLPds6/UBhF3oKLAIYzTFkUZ8YM4ULldSbbB1NOTlHzM5VnOlfTf6v4LUbDZhef7FZPYBl2CUONlwpimY+y7deMNtTEb2IWxeAxS3bMzs9ezTLXfo3EbhIid0Yv6/KeQ9tYRJ834ZEMYMRJFUuPz92yLVjm0yWamwHgpu9rQjBiNU8hxCrciEz5/xUAi0INXFN1fsC+X+CNEUQ9EibDb0nBH44C2ePOly69igfMoaS3vhHgq27MhND93YvKBtqD+eoMGjjAW+0kuRFF7DRmXX7MGQL7tG8uV5ZUH1v1zXc6upUX5cjL5ChZX1+iUp0NSRByqVP/JbxzkmsF/je3SZ81kKgdKpY1z/sB/6m1dY+Wv1wtOnMEdHOejxZORB3n3Dom8k9QukDY8ZE4Jon6tBjd3SIG+wL3t8iGoIkoTJ7MljGOKWdaGZalro41LZ9dxlBihuO/KAO0sw8SL1v+ZTnVNsABqccqfhTe545co9AO4J6ID9CR8JbZV1dLFkjm2K75TOK4shNjd6sFoMH/o+nsOByL9lcKJkTzw5YT4XAK04VdjgcC+/kevMk43IYQzkeagqNy3/kRFjlWX6xhrO0lbBNwiU2GRM7iLyij69FvZcRpf0bjzqFvHD+VP+q8sZW11Defpgx7Auffi4+BTmsRP2aAHDStASmqc9/+4CLh2abLCMQOdpXVYZhiNqOYJSkPhT2+M06qImKEGYwo2ufjHae+kHeta3iays7bue9Gvdrwx4fIK2AmU0/VPZu7NVdSaB7WNoNF8KL+yGJTagqTgL+ohQm/P5ZW1mG5MOS6WVLkm2US+v5T3eWIuZ5QgPXkZ6qZEOnRyAh/Zd9Gz4b/XfOdmZgBDUQDVzzXgFqKjbEwJV3uz3W9yJo4iPI+e3LGTxUFYDcOVRGSQn4gkDkSsG6leE1ckxo+dnFb6j21BtyEIlTax7tWu6r+PCdUyPluC5UOKrzTCmyT0DaOLeXVE10+kriN4TPaR+F4OWOkDJ4ILTrrpaCSsncBdie8D9qJjB3YyoXrOO6Dl6Tw6igm9G0pwoGR2de0NZ010CFyTwf9ggg8PjFWWEXy2wD9tKmtRvE13iZc6xOlXpmyMQX/YPtHR+i0w8dZqcu5k1lt42nI8z7USkQRTeWhj2vc5/N+5RsLJORCvFaWrv84IOoS3C/7LJgirOwvFKESqRq9C7egFTUTM9FzAJWsyXMiaI2atxuiiTTijxU1DPwUqTw67Zkg4pZ1R/gLJF8cjbA3AkqVuTvd4TAhHbAWLiaSnuntomQlaJRUCohIOb4Lx9wLGwZaff2XjCeazJ+s0TAxkRyEUGTgIkLsBZ3I9L3fNrnkDXwk6/lp4vjx608IE9WAFImarRtTLjftmVhP66r2FZ8r8B8z2dGZ4XI4H+KPo95/8CGsVXhaKF4DVf/u2PIFVXo1Dt5b+ST02l7GOut5jA2UzgbM4oymEz8c3NXdAfXv3+guHXvbM+5cVdQVIwj/O9d+3M+B8j+Fjs55Rum4s1Bcd7vsUjTXKXOz5gLXU5xIEa7SnshNXJQCnfh6qYRJO7Dg/xRG4mUAaN0Fa3e4hvO3aZRQXbekGNgj2oIuSDXV0Jy1ihs8T8qnDACD3Y64gYd411lnV6IC/32755XHfJP2gZhUMs/HE9R8rb2tkolHBTXiAik/yRoEQZJwtPS/EUIqFBEEiKZuxLg4XPnI9LCB3eBybu4xX/3bHPPtO9LRex7+f9wNgjmAuD9FQL5I6guvNT5llUx4+BQan4hIjfUPSZwUhg3oTc52u79nDqh4Bkhvf++SVWxZHf9P0SAnWveHpZIsjLqoTQExHuk4LJB0LFw3N4r4l+bhsVJcom6yTqjWnefvWN0RUyT49yXegUi2MmUi9S5g+fLl4b5/JijW95FtDaaXFpaTGh/Tkt1hI1DfRnEKSJqsD+V5O9bkZ6YQDWRQe7sAQPdv9vnwEuPmmbr1W7+MuWW94srYAs9wtu2BkgebKnvPbQkjFkrxoFslR5Dgu4+Bu5McDQhIS/WcZ2cRTDLGOV1ecwWoxZ7/tQ9vPou4Ilu2vj9+BIs/uvIiU3s798Dyih59sWLSCJ/efnfjHHtK03tBJlOSbnG/Mp5OhqDmIxwxnZ1PGjclDDyohispeBiJD0czeRHjk8z2NmYdbI3nWjU6mHyy51o0ceKIigKy/BVFzRCIm6rvWw7zFgCOSy8bGftA952v34sKuN3V6MzibmJYtETsTt0RUEB93KzZNJkf+TqSPFzf343WIuVgMnWGpDcAyBHGe3/ErLroZIrpGFL2qhI44Je0HM2aXz5L5COqcaiaAShVsW3F84GHHVAGdTWexqgxdJg8qZ543iPjdXgADZsgBzKq8uxnpSzh2P43e9O7Kc+evpIiQmo1giBRELqpoq0GfWm3pQDbUNef5qllC0U/0ZiNtnObfPMEqABPgNopPWOwa1eC2C1/qRbqVkEtpQ0sVyBGf2ZkvvM2EoOdp5ScXw7Ux7Q+SvAE1Cezifq2x5z/7ICB6zTjJiiHppH8ytp4fGOqBHZNAvUrZBQHxtqcvaLguuD2hNFj54ujOGd1yllAUXTeWfU6U+VWpJI82IKJcJ2lxXCbU2HmUnPnMTUpurgsYnMeR5hRSU+rcekTxM9zAqohTJLXJmClrwTchC3MV44HM84Lb7ZzDoF2kWo68F4MY+v3xoNCIipWDozHLmQUB3WTrz+KqPcv+9TbvIjzma5MZ9jdbiSF2tq7uSvV8qeKQ10nGO8dLbZvavYhhRBt38C0k8eyjWAk/+8LmGIZMWKLvXYAg9IIl6+Bq9QIQQhBcov7vUxGifYsL2NUbEP4JwTrIVo0f6r//l75O+qRQOX1ZUgRh7+NNi4LioTnKDL69guTmWToOIiJrFIT8yiVd+neDxQVxg7W9MaQrCKYXe3udjwVnBWDX0ah5iNzoh33ykljNpuL0zCDfB76pc2IL3T7mDsqY06sImXr0Y/3Y5uq4k/SEq0QQFwRwfzFjlyvB9KiZIo3l+tvI5BdODou4KLtJ6z/X6tiUhym7jr3L5w/ej+CgqFEGEsgZKpqHnf3tNoZulTz3J+zc9p9SCBJFrDBwDXTAXsFFCbdt/K1nNSRIRSIokKxQIJ2LlL48aNhgDuMJCRkCJYrutHZ/VHFaX3M2izokyEM9sTGjC446tVRTnt+u7G0pmWcIm5wsXIk860Z6nlb/LcKdqF4abhFPzLVjoJQfVhGCCYCDI0X56NqCyrbDSfjTdZMU6qmlC7cVnmB19EaA8gPq4/QVpyfK4UeauFBS2Uk6LUBifHjkoHOO5c7nHD9WD867esNBpn/Y8eAch9hokf1DyCVE8EnianNSD3WGXrDy1Qr2SFy6bfz1AQhVyTmkniVrQ9iK/4nO/KkZivIwOzAfMAcGBSsOAwIaBBRLqsFVLJv5fBtisqneMV8JygIeNAQUSGBF4exdBYN0eXUcoQ6MTA4EczoCAgfQ
    pfx-password: ${CLIENT_CERTIFICATE_PASSWORD:}
    pfx-type: PKCS12