logging.level:
  root: INFO

spring:
  application:
    name: rtp-activator
  data:
    mongodb:
      uri: ${COSMOS_ACCOUNT_RTP_CONNECTION_STRING:mongodb://localhost:27017}
      database: ${DB_NAME:activation}
      uuid-representation: standard
  cloud:
    azure:
      monitor:
        connection-string: ${APPLICATIONINSIGHTS_CONNECTION_STRING:}

activation:
  base-url: ${BASE_URL:http://localhost}

# enable spring boot actuator health endpoint
management:
  endpoints:
    enabled-by-default: false
    web.exposure.include: health
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
  otlp:
    tracing:
      export:
        type: console
  #repository
  health.mongo.enabled: false

otel:
  instrumentation:
    mongo:
      enabled: true
    logback-appender:
      experimental:
        capture-mdc-attributes: "*"
