logging.level:
  root: INFO
  com.azure.monitor.opentelemetry.exporter.implementation.builders.TelemetryTruncation: ERROR

spring:
  application:
    name: rtp-activator
  data:
    mongodb:
      uri: ${COSMOS_ACCOUNT_RTP_CONNECTION_STRING:mongodb://localhost:27017}
      database: ${DB_NAME:rtp}

activation.base-url: ${BASE_URL:http://localhost}

# enable spring boot actuator health endpoint
management:
  endpoints:
    enabled-by-default: false
    web.exposure.include: health
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true

#repository
  health.mongo.enabled: false


service-provider:
  activation:
    api-version: v1

# OpenTelemetry
applicationinsights:
  enabled: true
  connection-string: ${APPLICATIONINSIGHTS_CONNECTION_STRING:myconnectionstring}

otel:
  log:
    level: ${OPENTELEMETRY_LOG_LEVEL:INFO}
  traces:
    sampler:
      probability: 1.0 # sample probability for tracing (spans)
  metric:
    export:
      interval: 60000 # sampling rate for metrics (millis)
  instrumentation:
    logback-appender:
      enabled: true # enable logback instrumentation
    micrometer:
      enabled: false
    mongo:
      enabled: true
    spring-webflux:
      enabled: true
    reactor:
      enabled: true
