logging.level:
  root: DEBUG

spring:
  application:
    name: rtp-activator
  data:
    mongodb:
      uri: ${COSMOS_ACCOUNT_RTP_CONNECTION_STRING:mongodb://localhost:27017}
      database: ${DB_NAME:rtp}

activation.base-url: ${BASE_URL:http://localhost}

# enable spring boot actuator health endpoint
management:
  endpoints:
    enabled-by-default: false
    web.exposure.include: health
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
  otlp:
    tracing:
      export:
        type: console
#repository
  health.mongo.enabled: false

service-provider:
  base-url: ${SP_BASE_URL:http://localhost:8080/rtps/}
  activation:
    api-version: v1
  send:
    epc-mock-url: ${EPC_MOCK_URL:https://api-rtp.dev.cstar.pagopa.it/rtp/mock}
    retry:
      max-attempts: ${EPC_SEND_RETRY_MAX_ATTEMPTS:3}
      backoff-min-duration: ${EPC_SEND_RETRY_BACKOFF_MIN_DURATION_MS:1000}
      backoff-jitter: ${EPC_SEND_RETRY_BACKOFF_JITTER:0.75}

otel:
  instrumentation:
    mongo:
      enabled: true

cache:
  params:
    - name: registry-data
      maximum-size: 1
      expire-after-write: 1d

blob-storage:
  storage-account-name: ${AZURE_STORAGE_ACCOUNT_NAME:cstardweurtpblobstorage}
  container-name: ${AZURE_STORAGE_CONTAINER_NAME:rtp-debtor-service-provider}
  blob-name: ${AZURE_BLOB_NAME:serviceregistry.json}
  managed-identity: ${IDENTITY_CLIENT_ID:}

client:
  client-secret-cbi: ${CLIENT_SECRET_CBI:test}
  ssl:
    pfx-file: ${CLIENT_CERTIFICATE}
    pfx-password: ${CLIENT_CERTIFICATE_PASSWORD:}
    pfx-type: PKCS12
