logging.level:
  root: INFO
  io:
    opentelemetry: DEBUG

spring:
  application:
    name: rtp-activator
  data:
    mongodb:
      uri: ${COSMOS_ACCOUNT_RTP_CONNECTION_STRING:mongodb://localhost:27017}
      database: ${DB_NAME:rtp}

activation.base-url: ${BASE_URL:http://localhost}

# enable spring boot actuator health endpoint
management:
  endpoints:
    enabled-by-default: false
    web.exposure.include: health
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
#repository
  health.mongo.enabled: false


# OpenTelemetry
applicationinsights:
  enabled: true
  connection-string: ${APPLICATIONINSIGHTS_CONNECTION_STRING:myconnectionstring}

service-provider:
  activation:
    api-version: v1
