logging.level:
  root: INFO

spring:
  application:
    name: rtp-activator
  data:
    mongodb:
      uri: ${COSMOS_ACCOUNT_RTP_CONNECTION_STRING:mongodb://localhost:27017}
      database: ${DB_NAME:rtp}

activation.base-url: ${BASE_URL:http://localhost}

# enable spring boot actuator health endpoint
management:
  endpoints:
    enabled-by-default: false
    web.exposure.include: health
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true

#repository
  health.mongo.enabled: false


service-provider:
  activation:
    api-version: v1


otel:
  instrumentation:
    mongo:
      enabled: true 
      statement-sanitizer.enabled: true

    spring-webflux:
      enabled: true

    reactor:
      enabled: true