name: Component test

on:
  workflow_dispatch:
  push:
    branches:
      - SRTP-*

jobs:
  component-test:
    runs-on: ubuntu-24.04
    environment: cstar-u-weu-rtp

    steps:
      #
      # Checkout the source code
      #
      - name: Checkout the source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
        with:
          fetch-depth: 0

      #
      # Install Node
      #
      - name: Install Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af #v4.1.0
        with:
          node-version: "20.18.0"
      #
      # Install Newman.
      #
      - name: Install Newman
        if: steps.semantic.outputs.new_release_published == 'true'
        run: npm install -g newman

      #
      # Run Postman collection.
      #
      - name: Run Postman collection
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          newman run src/test/postman/RTP-component-test.postman_collection.json \
            -e src/test/postman/uat.postman_environment.json \
            --env-var "payer-sp-client-secret=${{ secrets.PAYER_SP_CLIENT_SECRET }}" \
            --env-var "pagopa-sp-client-secret=${{ secrets.PAGOPA_SP_CLIENT_SECRET }}"