name: "Send notification"

on:
  workflow_call:
    inputs:
      CVE_CRITICAL:
        required: true
        type: string
      CVE_HIGH:
        required: true
        type: string
      CVE_MEDIUM:
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  Notify:
    name: Notify Slack
    runs-on: ubuntu-latest
    environment: itn-dev
    steps:
      - name: Send notification to Slack
        id: slack
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a #v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            blocks:
              - type: "header"
                text:
                  type: "plain_text"
                  text: "[ ${{ github.event.repository.name }} ]"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: |
                    `CRITICAL` : *${{ inputs.CVE_CRITICAL }}*
                    `HIGH` : *${{ inputs.CVE_HIGH }}*
                    `MEDIUM` : *${{ inputs.CVE_MEDIUM }}*
                    ${{ github.event_name == 'pull_request' && format("See PR diff → <https://github.com/{0}/pull/{1}/files>", github.repository, github.event.pull_request.number) || format("See details on GitHub → <https://github.com/{0}/security/code-scanning>", github.repository) }}
